name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: centos:7

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lucagervasi/bacula-web:$(date +%s)
